spring:
  datasource:
    url: ${H2_URL}
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul
          batch_size: 1000
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.sql: debug
