name: 프로젝트 빌드 및 업로드

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  AWS_REGION: ap-northeast-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew에 실행 권한 부여
        run: chmod +x gradlew

      - name: properties 생성
        run: |
          mkdir -p ./src/main/resources/
          echo "${{ secrets.APPLICATION }}"
          cat ./src/main/resources/application-prod.yml

      - name: Gradle 빌드 (테스트 제외)
        run: ./gradlew clean build --exclude-task test

      - name: AWS 인증
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3에 업로드
        run: |
          aws deploy push \
          --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }} \
          --ignore-hidden-files \
          --s3-location s3://${{ secrets.AWS_S3_BUCKET }}/$GITHUB_SHA.zip \
          --source .

      - name: EC2에 배포
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_GROUP }} \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET }},key=$GITHUB_SHA.zip,bundleType=zip